<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>RSL Documentation Statements Syntax</string>
	<key>fileTypes</key>
	<array>
		<string>statements</string>
	</array>
</dict>
</plist>
